In [37]:
import numpy as np
c = np.random.randn(3,3)
d = np.random.normal(0,1,[2,3,4])
quanlianjie_1=np.random.randn(3,3)
b1=np.random.rand(1,3)
quanlianjie_2=np.random.randn(3,2)
X=np.array([22,35,86])
Y=np.dot(quanlianjie_2.T,(np.dot(quanlianjie_1,X.T)+b1).reshape(3,1))


In [41]:
import tensorflow as tf
import numpy as np
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant([[4]]) #不加括号就会是0维张量
print(rank_0_tensor)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [42]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [43]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [44]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
                    
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [46]:
a=np.random.randn(4,4)
b=np.random.randn(4,5,6)
tensor1=tf.constant(a)
tensor2=tf.constant(b)
print(tensor2)

tf.Tensor(
[[[-0.39389187 -0.15390557  0.21872142 -0.93236267 -0.0139193
    0.4370245 ]
  [-1.75995974  0.19289489  1.12030367 -0.05633886  0.84569309
   -0.59836147]
  [-0.6855273  -0.48851085 -0.28642387  0.92876677 -3.32450094
   -0.34976974]
  [ 0.41760983  0.32994778  1.9371952  -1.00367738  0.40359388
    0.84740543]
  [-0.29799075 -0.05314055  1.46010108 -1.01659934 -1.07611134
   -0.67257631]]

 [[ 0.04273928 -1.77589657  0.56035459 -0.87562061  1.21739581
   -0.04553259]
  [ 0.31163146  1.75780004 -0.09297103  1.39827226 -2.11408773
    0.44291575]
  [ 0.6148668  -1.87244056 -1.97573254  2.2236535  -0.17342473
   -0.16308491]
  [ 0.75950313 -0.97812966 -1.15580914 -0.33708249  0.64934877
    1.16275227]
  [ 0.67610025  1.07421221 -0.57428321 -0.1145297  -0.04703879
    0.99926951]]

 [[-0.18312831 -2.38447421  0.22053202 -1.38622148  0.46833287
   -1.45430329]
  [-0.79820025 -0.19087391 -0.92551113 -0.85317224 -0.37038944
    0.31964272]
  [ 0.21390393 -1.43466728 -1.2791252 

In [50]:
x = tf.constant(1.0)

with tf.GradientTape() as t:
    t.watch(x)
    z = tf.exp(x)+tf.multiply(x,x)

print(t.gradient(z,x))

tf.Tensor(4.7182817, shape=(), dtype=float32)
